apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "chaos-generator"
  title: "Chaos Generator"
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: RyanJKS/chaos-generator
  description: "Controlled HTTP event traffic for observing systems under load"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/ryanjks"
